CREATE TABLE User (
	ID integer PRIMARY KEY AUTOINCREMENT,
	NAME text PRIMARY KEY AUTOINCREMENT,
	PHONENUMBER integer PRIMARY KEY AUTOINCREMENT,
	ADDRESS blob PRIMARY KEY AUTOINCREMENT,
	CARDDETAILS blob PRIMARY KEY AUTOINCREMENT,
	REGISTRATIONDATE datetime PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Transactions (
	FROM USER ID integer PRIMARY KEY AUTOINCREMENT,
	TO USER ID integer PRIMARY KEY AUTOINCREMENT,
	TRANSACTION DATE date PRIMARY KEY AUTOINCREMENT,
	AMOUNT float PRIMARY KEY AUTOINCREMENT,
	CURRENCY float PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE "Businesses User" (
	ID integer PRIMARY KEY AUTOINCREMENT,
	NAME text PRIMARY KEY AUTOINCREMENT,
	PHONENUMBER integer PRIMARY KEY AUTOINCREMENT,
	ADDRESS blob PRIMARY KEY AUTOINCREMENT,
	CARDDETAILS blob PRIMARY KEY AUTOINCREMENT,
	REGISTRATIONDATE datetime PRIMARY KEY AUTOINCREMENT
);

